<?php

/**
 * @var \Hiberus\Rodriguez\Block\Index $block
 */
$alumnos = $block->getAlumno();
$notas = $block->getAverageMarks();
$notaMinima = $block->getNota();
$i = 0;
$elementos = $block->getElementos();
$maxMarks = $block->getMaxMarks();
?>

<h2 class="title">Alumnos</h2>

<!-- Ejercicio 7 js -->
<button class="button" id="desplegar">Alumnos/as</button>
<!-- Ejercicio 9 js -->
<button class="button" id="notaMasAlta">Nota mas alta</button>


<div id="details"><!-- div toggle btn -->

    <?php

    foreach ($alumnos as $alumno) {
        // Para que salga rojo suspensos y verdes aprobados
        if ($i++ == $elementos) break;
        if ($alumno->getMark() > $notaMinima) { // 4.9
            $classEvaluation = "approved";
        } else {
            $classEvaluation = "suspensed";
        }
        ?>

        <ul>
            <li><span class="textBold">Nombre </span><?= $alumno->getFirstName(); ?></li>
            <li><span class="textBold">Apellidos </span><?= $alumno->getLastName(); ?></li>
            <li class="<?= $classEvaluation ?>">Nota <?= $alumno->getMark(); ?></li>
        </ul>

    <?php } ?>

</div> <!-- div toggle btn -->


<div class="calculate">
<p class="textBold textColor">Las 3 mayores notas obtenidas<p/>
|
<?php foreach($maxMarks as $mark) { ?>
    <?= $mark ?> |
<?php } ?>

<p class="textBold textColor"> Media de notas </p>
<p><?= $notas ?></p>

<p class="textBold textColor"> Total de alumnos </p>
<p><?= (count($alumnos)) ?></p>
</div>

<script>
    var maxNote = <?= $block->getMaxMark() ?>
</script>


<script>
    require(['jquery', 'toggle'], function ($, myscript) {
        myscript('#desplegar', '#details');
    });
    require(['jquery', 'alert'], function($, alertNotaAlta) {
        alertNotaAlta('#notaMasAlta');
    });
</script>

