<?php

/**
 * @var \Hiberus\Rodriguez\Block\Index $block
 */
$alumnos = $block->getAlumno();
$notas = $block->getAverageMarks()
?>

<h2 class="title">Alumnos</h2>

<!-- Ejercicio 7 js -->
<button id="desplegar">Desplegar</button>

<div id="details"><!-- div toggle btn -->

    <?php

    foreach ($alumnos as $alumno) {
    // Para que salga rojo suspensos y verdes aprobados
        ?>

        <ul>
            <li>Nombre:<?= $alumno->getFirstName(); ?></li>
            <li>Apellido: <?= $alumno->getLastName(); ?></li>
            <li>Nota:<?= $alumno->getMark(); ?></li>
        </ul>

    <?php } ?>

</div> <!-- div toggle btn -->

<p> Media de notas: <?= $notas ?> </p>
<p> Total de alumnos: <?= (count($alumnos)) ?> </p>

<script>
    require(['jquery', 'toggle'], function ($, myscript) {
        myscript('#desplegar', '#details');
    });
</script>

